---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

#- name: Copy the code from repository
#  git: repo={{ repository }} dest=/var/www/html/

- name: Creates the index.html file
  copy: src=/var/lib/jenkins/workspace/project1-ansible/roles/web/tasks/index.html dest=/var/www/html/ owner:jenkins group:jenkins mode:0400

